@startuml
class Main{
 + static void main(String[] args)
}

class Bank{
 - String name
 - ArrayList<Customer> customers
 + Bank(String name)
 + void addCustomer(Customer)
 + String toString()
}

class Customer{
 - String name
 - int balance
 + Customer(String name, double balance)
 + void setBalance(double amount)
 + String toString()

}



Main *-- Bank
Bank *-- Customer

@enduml